export const projects = [
  // --- EXISTING PROJECTS ---
  {
    id: 1,
    title: "Cotton Thread on Cotton Belt",
    category: "Thesis Documentary",
    group: "film",
    year: "2026",
    type: "video",
    videoSrc: "/projects/cotton-thread/Teaser 2.mp4", 
    image: "/projects/cotton-thread/stills/preview.jpg", 
    description: "Cotton Thread on Cotton Belt follows Dipa Bhattarai, a Nepali student who arrives in Mississippi and starts threading eyebrows for friends in a dorm room, then turns that skill into a small mall kiosk and a second shop, until the Mississippi State Board of Cosmetology shuts her down and tells her to meet licensing rules that do not even teach threading. Instead of walking away, she takes the fight into public meetings and then into court, and her case helps change state law. Today, her business sits inside Walmart stores across Mississippi, and she pushes toward bigger expansion while carrying a tradition from home into the American South. The film follows an immigrant’s resilience through a young woman entrepreneur’s journey, showing how one immigrant can create a positive impact in the communities they move into."
  },
  {
    id: 2,
    title: "Nepal Landscapes",
    category: "Photography",
    group: "photos",
    year: "2020-2025",
    type: "gallery",
    image: "/projects/landscape/DSC06773.jpg", 
    galleryImages: [
      "/projects/landscape/DSC00029.jpg",
      "/projects/landscape/DSC05091.JPG",
      "/projects/landscape/DSC06863.jpg",
      "/projects/landscape/DSC06993.jpg",
      "/projects/landscape/DSC08772.JPG",
      "/projects/landscape/DSC08877.JPG",
      "/projects/landscape/DSC09771.jpg",
      "/projects/landscape/DSC09953.jpg",
      "/projects/landscape/DSC00038.jpg",
      "/projects/landscape/DSC06773.jpg",
      "/projects/landscape/DSC06946.jpg",
      "/projects/landscape/DSC07033.jpg",
      "/projects/landscape/DSC08843.JPG",
      "/projects/landscape/DSC09680.jpg",
      "/projects/landscape/DSC09842.jpg",
      "/projects/landscape/DSC09996.jpg",
      "/projects/landscape/DSC00223.jpg",
      "/projects/landscape/DSC06779.jpg",
      "/projects/landscape/DSC06963.jpg",
      "/projects/landscape/DSC08078.jpg",
      "/projects/landscape/DSC08850.JPG",
      "/projects/landscape/DSC09720.jpg",
      "/projects/landscape/DSC09851.jpg",
      "/projects/landscape/DSC09999.jpg"
    ]
  },
  {
    id: 3,
    title: "Mr. Brown",
    category: "Photo Essay",
    group: "photos",
    year: "2025",
    type: "gallery",
    image: "/projects/mr-brown/photos/cover.jpg",
    pdf: "/projects/mr-brown/statement final.pdf",
    galleryImages: [
      "/projects/mr-brown/Photo in sequence/1.jpg",
      "/projects/mr-brown/Photo in sequence/2.jpg",
      "/projects/mr-brown/Photo in sequence/3.jpg",
      "/projects/mr-brown/Photo in sequence/4.jpg",
      "/projects/mr-brown/Photo in sequence/5.jpg"
    ]
  },
  {
    id: 4,
    title: "Jere Allen",
    category: "Short Film",
    group: "film",
    year: "2024",
    type: "link", 
    url: "https://vimeo.com/941591505?fl=pl&fe=sh",
    image: "/projects/jere-allen/cover.png",
    description: "Jere Allen, an 80-year-old painter in Oxford, Mississippi, as he uses his grandmother's lessons to create beautiful oil Paintings. This film highlights his journey and passion, focusing on his beloved hummingbird series"
  },
  {
    id: 5,
    title: "South Trail",
    category: "Short Film",
    group: "film",
    year: '2023',
    type: "link",
    url: "https://vimeo.com/1157759347?share=copy&fl=sv&fe=ci",
    image: "/projects/south-trail/cover.jpg", 
    description:"A film about the South Trail, starting with the beauty of the jungle in the fall season. The perception of Wonder Walks, Mountain Bikers, and Runners about the South Trail. And end in the Winter season." 
  },
  {
    id: 6,
    title: "Interschool Basketball",
    category:"Photography",
    group: "sports",
    year: "2020",
    type: "gallery",
    image: "/projects/Interschool-basketball/100A3808.JPG",
    galleryImages: [
      "/projects/Interschool-basketball/100A3808.JPG",
      "/projects/Interschool-basketball/100A3924.JPG",
      "/projects/Interschool-basketball/100A4085.JPG",
      "/projects/Interschool-basketball/100A4095.JPG",
      "/projects/Interschool-basketball/100A4099.JPG",
      "/projects/Interschool-basketball/100A4147.JPG",
      "/projects/Interschool-basketball/100A4150.JPG",
      "/projects/Interschool-basketball/100A4183.JPG",
      "/projects/Interschool-basketball/100A4328.JPG",
      "/projects/Interschool-basketball/100A4363.JPG",
      "/projects/Interschool-basketball/DSC08419.JPG",
      "/projects/Interschool-basketball/DSC08420.JPG",
      "/projects/Interschool-basketball/DSC08518.JPG",
      "/projects/Interschool-basketball/DSC08519.JPG",
      "/projects/Interschool-basketball/DSC08531.JPG",
      "/projects/Interschool-basketball/DSC08533.JPG",
      "/projects/Interschool-basketball/DSC08546.JPG",
      "/projects/Interschool-basketball/DSC08729.JPG",
      "/projects/Interschool-basketball/DSC08892.JPG",
      "/projects/Interschool-basketball/DSC08893.JPG",
      "/projects/Interschool-basketball/DSC09007.JPG",
      "/projects/Interschool-basketball/DSC09019.JPG",
      "/projects/Interschool-basketball/DSC09089.JPG",
      "/projects/Interschool-basketball/ROS04191.JPG",
      "/projects/Interschool-basketball/ROS04195.JPG",
      "/projects/Interschool-basketball/ROS04318.JPG",
      "/projects/Interschool-basketball/ROS04347.JPG",
      "/projects/Interschool-basketball/ROS04348.JPG",
      "/projects/Interschool-basketball/ROS04349.JPG",
      "/projects/Interschool-basketball/ROS04350.JPG",
      "/projects/Interschool-basketball/ROS04415.JPG",
      "/projects/Interschool-basketball/ROS04429.JPG"
    ]
  },

  // --- NEW: TRAVEL FILMS (Group: film) ---
  {
    id: 101,
    title: "KORI - The Beautiful Highlands of Kaski",
    category: "Travel Film",
    group: "travel", // <--- NEW GROUP
    year: "2020",
    type: "link",
    url: "https://youtu.be/WnGWfHJQb5U",
    image: "https://img.youtube.com/vi/WnGWfHJQb5U/maxresdefault.jpg",
    description: "Lockdown Series Ep 2: Exploring the stunning highlands of Kaski."
  },
  {
    id: 102,
    title: "Chola Circuit Trek & Everest Base Camp",
    category: "Travel Film",
    group: "travel",
    year: "2021",
    type: "link",
    url: "https://youtu.be/LolExdWgPDU",
    image: "https://img.youtube.com/vi/LolExdWgPDU/maxresdefault.jpg",
    description: "Ep Two: Hiking to Kalapathar and the empty Everest Base Camp during the lockdown winter."
  },
  {
    id: 103,
    title: "Badimalika & Tribeni Patan",
    category: "Travel Film",
    group: "travel",
    year: "2021",
    type: "link",
    url: "https://youtu.be/9iXhMmPtqRE",
    image: "https://img.youtube.com/vi/9iXhMmPtqRE/maxresdefault.jpg",
    description: "A pilgrimage to the holy Badimalika via the treacherous Kalikot route."
  },
  {
    id: 104,
    title: "Khumai Dada - Great Machhapuchhre Trail",
    category: "Travel Film",
    group: "travel",
    year: "2022",
    type: "link",
    url: "https://youtu.be/C0xkXjMK8Jk",
    image: "https://img.youtube.com/vi/C0xkXjMK8Jk/maxresdefault.jpg",
    description: "Exploring the pristine snow and magnificent views of Mt. Machhapuchhre from Khumai Dada."
  },
  {
    id: 105,
    title: "Ramaroshan - Episode I",
    category: "Travel Film",
    group: "travel",
    year: "2021",
    type: "link",
    url: "https://youtu.be/VTq6NA18xeM",
    image: "https://img.youtube.com/vi/VTq6NA18xeM/maxresdefault.jpg",
    description: "A journey through the 'Land of 12 Lakes and 18 Meadows' in Achham."
  },
  {
    id: 106,
    title: "People & Culture of Madhesh Pradesh",
    category: "Travel Film",
    group: "travel",
    year: "2022",
    type: "link",
    url: "https://youtu.be/SBEkfMAD6VM",
    image: "https://img.youtube.com/vi/SBEkfMAD6VM/maxresdefault.jpg",
    description: "Imagine Nepal: A cinematic deep dive into the culture of the Madhesh province."
  },
  {
    id: 107,
    title: "Saipal Base Camp - Road Trip (Ep 1)",
    category: "Travel Film",
    group: "travel",
    year: "2022",
    type: "link",
    url: "https://youtu.be/uGTjK0m_NQY",
    image: "https://img.youtube.com/vi/uGTjK0m_NQY/maxresdefault.jpg",
    description: "The beginning of an epic journey to Far West Nepal, Bajhang."
  },
  {
    id: 108,
    title: "Saipal Base Camp - The Trek (Ep 2)",
    category: "Travel Film",
    group: "travel",
    year: "2022",
    type: "link",
    url: "https://youtu.be/jid2_wtB7kQ",
    image: "https://img.youtube.com/vi/jid2_wtB7kQ/maxresdefault.jpg",
    description: "Hiking through landslides and beautiful forests to reach the foot of Mt. Saipal."
  },
  {
    id: 109,
    title: "Raidhungi & Saipal Finale",
    category: "Travel Film",
    group: "travel",
    year: "2023",
    type: "link",
    url: "https://youtu.be/c0u_ppZVsLk",
    image: "https://img.youtube.com/vi/c0u_ppZVsLk/maxresdefault.jpg",
    description: "Exploring the untouched beauty of the Raidhungi area in the finale of the Bajhang series."
  },
  {
    id: 110,
    title: "Holi in Janakpur",
    category: "Travel Film",
    group: "travel",
    year: "2024",
    type: "link",
    url: "https://youtu.be/pqHYiqfaqNI",
    image: "https://img.youtube.com/vi/pqHYiqfaqNI/maxresdefault.jpg",
    description: "Experiencing the vibrant festival of colors in the holy city of Janakpur."
  },
  {
    id: 111,
    title: "KANCHANJUNGA Base Camp - Ep 1",
    category: "Travel Film",
    group: "travel",
    year: "2020",
    type: "link",
    url: "https://youtu.be/BBa0F1kzToI",
    image: "https://img.youtube.com/vi/BBa0F1kzToI/maxresdefault.jpg",
    description: "Journey to Oktang Base Camp of the third highest mountain in the world."
  },
  {
    id: 112,
    title: "KANCHANJUNGA Base Camp - Ep 2",
    category: "Travel Film",
    group: "travel",
    year: "2020",
    type: "link",
    url: "https://youtu.be/6itDcVxx-s4",
    image: "https://img.youtube.com/vi/6itDcVxx-s4/maxresdefault.jpg",
    description: "Exploring Pangpema North Base Camp."
  },
  {
    id: 113,
    title: "Lockdown Series - Meme Pokhari",
    category: "Travel Film",
    group: "travel",
    year: "2020",
    type: "link",
    url: "https://youtu.be/ELgO9sT7uW0",
    image: "https://img.youtube.com/vi/ELgO9sT7uW0/maxresdefault.jpg",
    description: "Discovering the hidden Meme Pokhari in Lamjung."
  },
   {
    id: 114,
    title: "GOKYO - Chola Circuit Ep Three - Chola Pass, Gokyo and Gokyo Ri",
    category: "Travel Film",
    group: "travel",
    year: "2020",
    type: "link",
    url: "https://youtu.be/zIMONZdb188",
    image: "https://img.youtube.com/vi/zIMONZdb188/maxresdefault.jpg",
    description: "Cinematic travel documentary capturing remote landscapes."
  },
   {
    id: 115,
    title: "NESO - The Dying Festival of The Kanchanjungas, Ghunsa, Taplejung!",
    category: "Travel Film",
    group: "travel",
    year: "2020",
    type: "link",
    url: "https://youtu.be/ozvsYlEz-Lg",
    image: "https://img.youtube.com/vi/ozvsYlEz-Lg/maxresdefault.jpg",
    description: "Cinematic travel documentary capturing remote landscapes."
  },

  // --- COMMERCIALS ---
  {
    id: 201,
    title: "dZi Anthem Video",
    category: "Commercial",
    group: "commercial", // <--- NEW GROUP
    year: "2019",
    type: "link",
    url: "https://www.youtube.com/watch?v=UCnZdbGK2mM",
    image: "https://img.youtube.com/vi/UCnZdbGK2mM/maxresdefault.jpg",
    description: "Anthem video for dZi Foundation, partnering with isolated communities in Nepal."
  },
  {
    id: 202,
    title: "Dhodeni Water Project",
    category: "Commercial",
    group: "commercial",
    year: "2020",
    type: "link",
    url: "https://www.youtube.com/watch?v=xyQvkZGTITg",
    image: "https://img.youtube.com/vi/xyQvkZGTITg/maxresdefault.jpg",
    description: "Documenting the impact of clean water projects in rural Nepal."
  }
];